Feature/developer booklet changes
treeverse/onboarding pull request #1
Opened 2022-01-02 15:51 UTC by Jonathan-Rosenberg

1. Two typo fixes
2. Added a possible case if someone defined postgres with a password
3.  Running from the IDE: added the `go run` command before the file

2022-01-02 17:11 UTC, nopcoder reviewed
comment about the run itself.
markdown numbering is done automatically.
just keep them all 1.

2022-01-02 17:11 UTC, nopcoder commented on booklet.md
> +Open the project in your IDE (ask your buddy for an IntelliJ license), and run `go run cmd/lakefs/main.go`.
Think the idea here was to select the run option while selecting the specific run.go. The IDE will create a configuration profile to run and debug it.

2022-01-02 19:48 UTC, johnnyaug requested changes
Thanks! See comment

2022-01-02 19:48 UTC, johnnyaug commented on booklet.md
> +Open the project in your IDE (ask your buddy for an IntelliJ license), and run `go run cmd/lakefs/main.go`.
Yes, that was the idea. I agree that it wasn't the best phrasing.
Perhaps ```...and create a run configuration for the file `cmd/lakefs/main.go`. ```

2022-01-03 08:23 UTC, Jonathan-Rosenberg commented on booklet.md
> +Open the project in your IDE (ask your buddy for an IntelliJ license), and run `go run cmd/lakefs/main.go`.
👍

2022-01-03 09:15 UTC, nopcoder approved these changes

2022-01-04 14:47 UTC, johnnyaug approved these changes

2022-01-04 14:51 UTC, merged